name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Runs when you push a tag like v1.0.0

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List current folder structure
        run: |
          echo "Root directory:"
          ls -la
          echo "Possible build folders:"
          ls -la build || true
          ls -la dist || true
          ls -la out || true

      - name: Zip build output
        run: |
          mkdir -p release
          if [ -d "build" ]; then
            zip -r release/build.zip build/
          elif [ -d "dist" ]; then
            zip -r release/build.zip dist/
          elif [ -d "out" ]; then
            zip -r release/build.zip out/
          else
            echo "❌ No known build folder found (build/, dist/, or out/)."
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}